GG-8006 improve scala 3 migration
hmrc/pact-broker-frontend pull request #25
Opened 2024-08-14 12:26 UTC by szabolcs-szilagyi-hmrc

2024-08-20 09:28 UTC, dg-21-hmrc requested changes
Everything looks ok, the only thing I'd do is add some info for the next person as to why we are commenting out those compiler options.
Also I don't know if we should heed the bot warning to update sbt-plugin to 3.0.3 to match what bootstrap uses

2024-08-20 09:28 UTC, dg-21-hmrc commented on build.sbt
> +//      "-Xfatal-warnings"
I would add a comment here saying why we are commenting and when we can uncomment

2024-08-20 15:42 UTC, dg-21-hmrc approved these changes, later dismissed

2024-08-21 12:11 UTC, szabolcs-szilagyi-hmrc commented on build.sbt
> +//      "-Xfatal-warnings"
You are right. I added the explanation

2024-08-21 12:22 UTC, dg-21-hmrc approved these changes

2024-08-30 15:35 UTC, merged